# cloudbuild.yaml

steps:
  # Step 1: Build the application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/vivid-fragment-410115/sample-node-repo/samplenodeapp:latest', '.']
  
  # Step 2: Run tests
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', 'us-central1-docker.pkg.dev/vivid-fragment-410115/sample-node-repo/samplenodeapp:latest', 'npm', 'test']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '']

  # Step 4: Deploy the application (example for Cloud Run)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy my-app \
          --image  us-central1-docker.pkg.dev/vivid-fragment-410115/sample-node-repo/samplenodeapp:latest\
          --platform managed \
          --region  us-central1\
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY  # or you can choose other logging options

# If you want to specify a service account
#service_account:
